version: "3.9"

services:
  weather-app:
    image: fabriciobaiao/weather-pipeline:latest
    container_name: weather-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/weather

  mongo:
    image: mongo:6.0
    container_name: weather-app
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  scheduler:
    image: teu-usuario-dockerhub/weather-app:latest
    container_name: weather-scheduler
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - ./data:/app/data
    environment:
      - MONGO_URI=mongodb://mongo:27017/weather
    command: >
      sh -c "echo '0 11,23 * * * python /app/src/main.py >> /proc/1/fd/1 2>&1' > /etc/crontabs/root
             && crond -f -d 8"
    restart: always

volumes:
  mongo_data:
